{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-orm",
    "version": "5.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "62bllhdns5az3hsr52svr7rfgq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-orm-5.3.3.jar",
          "url": "spring-orm-5.3.3.jar",
          "size": 200261,
          "sha512": "3207f8385a8d56505634a58fbe82c89e4532ea4ac0608876ae8bde0b26b4f4ac976f749cee08a5c911d3be0732b6dc28a8f875489a816c5a1e61379332a5e2ba",
          "sha256": "82faf6132a312151a57b0105893bc83a60029089b63a05888b40728799a77811",
          "sha1": "2d8034e7982bd43ff7eaaa8a0ba30f31abf72410",
          "md5": "de23a15345c0e57216a3977ac1812821"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-jdbc",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-orm-5.3.3.jar",
          "url": "spring-orm-5.3.3.jar",
          "size": 200261,
          "sha512": "3207f8385a8d56505634a58fbe82c89e4532ea4ac0608876ae8bde0b26b4f4ac976f749cee08a5c911d3be0732b6dc28a8f875489a816c5a1e61379332a5e2ba",
          "sha256": "82faf6132a312151a57b0105893bc83a60029089b63a05888b40728799a77811",
          "sha1": "2d8034e7982bd43ff7eaaa8a0ba30f31abf72410",
          "md5": "de23a15345c0e57216a3977ac1812821"
        }
      ]
    }
  ]
}
