{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xiu4wbhcdnfo3k3sp26u3m4ssa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.4.2.jar",
          "url": "spring-boot-starter-2.4.2.jar",
          "size": 4769,
          "sha512": "deb192e26784f4fba2401d59521b953bc45f0d221d5d38cb28b3b1df1ebd40b4a6d6a2615022babe47bdca2b2d1360a9f9d41f1e0316efb30643541bb2b20634",
          "sha256": "6dd063f9b2f809b26176e4fdd2e4d4bd42eccb83dedc1437599677ad16e17d65",
          "sha1": "126908b151a4666ead4e10ce002dd3bf34c4e366",
          "md5": "b7f1c09f59894c2d5b9bdce40bdd6094"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.3"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.27"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.4.2.jar",
          "url": "spring-boot-starter-2.4.2.jar",
          "size": 4769,
          "sha512": "deb192e26784f4fba2401d59521b953bc45f0d221d5d38cb28b3b1df1ebd40b4a6d6a2615022babe47bdca2b2d1360a9f9d41f1e0316efb30643541bb2b20634",
          "sha256": "6dd063f9b2f809b26176e4fdd2e4d4bd42eccb83dedc1437599677ad16e17d65",
          "sha1": "126908b151a4666ead4e10ce002dd3bf34c4e366",
          "md5": "b7f1c09f59894c2d5b9bdce40bdd6094"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.4.2-javadoc.jar",
          "url": "spring-boot-starter-2.4.2-javadoc.jar",
          "size": 4738,
          "sha512": "5368cfa568e6f765934fef95dede96a1369215c7ce0323d852ae01d8d84da154c217ebb3546291d70890f78c0195552c9022b27ff2df6b9ce936b58cde3e4d68",
          "sha256": "addbff38337ee8737bb75c4f5b07b90181dd528e01932a83f75c1b004ecfbd27",
          "sha1": "2703194dba931392ad78b12f6b8d4a9cdbb949dd",
          "md5": "45b532a8d1e7e55303a56bf010991f1c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.4.2-sources.jar",
          "url": "spring-boot-starter-2.4.2-sources.jar",
          "size": 4736,
          "sha512": "3ef65588ff51099d8ebae03c81c60440f103388e292735ec290af879683feb74463dd7a0724d33245ca659d1dbc3231d96363993fcd5c44c177eac3169f28bdf",
          "sha256": "b21f13113ad530be86e1061b2abbe9019358e636407b69530862478b6a4ff236",
          "sha1": "33d556b1b7f20ff0f485131c2c5b91a94627ef7c",
          "md5": "cddc2b885f7b13012cbff6f956b967b9"
        }
      ]
    }
  ]
}
