{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xiu4wbhcdnfo3k3sp26u3m4ssa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.27.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.4.3"
          },
          "excludes": [
            {
              "group": "org.aspectj",
              "module": "aspectjrt"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.4.2.jar",
          "url": "spring-boot-starter-data-jpa-2.4.2.jar",
          "size": 4758,
          "sha512": "2cc80c9be02c2ee4406e5e8a085b776f040d7ce5f0d7bedb382c24321c23189995b95993941e0e8dda5a52cab2cd672e0ea7ba79d59130e49c1490b2a7044c65",
          "sha256": "03ed944c33e59767766e1854bd432c3ea1b37208d8dbd82cf3212c9c775d797b",
          "sha1": "4c703d6746355d0d894fc22488c8756b8fe25d29",
          "md5": "ca54b356f3ec479335f645892a2d915d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.27.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.4.3"
          },
          "excludes": [
            {
              "group": "org.aspectj",
              "module": "aspectjrt"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.4.2.jar",
          "url": "spring-boot-starter-data-jpa-2.4.2.jar",
          "size": 4758,
          "sha512": "2cc80c9be02c2ee4406e5e8a085b776f040d7ce5f0d7bedb382c24321c23189995b95993941e0e8dda5a52cab2cd672e0ea7ba79d59130e49c1490b2a7044c65",
          "sha256": "03ed944c33e59767766e1854bd432c3ea1b37208d8dbd82cf3212c9c775d797b",
          "sha1": "4c703d6746355d0d894fc22488c8756b8fe25d29",
          "md5": "ca54b356f3ec479335f645892a2d915d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.4.2-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.4.2-javadoc.jar",
          "size": 4749,
          "sha512": "7a8790a7af1972025451d6012f317ed312b048e3c66aa963ec7f5a2de3b41b7f70817ac9e86928b548eaaec4425993ba7aaaf493699ac4c649e6fa3bd65155d9",
          "sha256": "749870aa91986b3e22897417d7ac0179f762132a77524a4d0ee4f02e897f613c",
          "sha1": "e40a5b537bc36030eb6ee8312bda6fc5c90bc337",
          "md5": "9ba127ccc6d9199274b667110b5fa9e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.4.2-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.4.2-sources.jar",
          "size": 4747,
          "sha512": "76574b61b166f562f9523432699eb48790990d5d26e553ecaa41f87fd94e44297165fd19312414549777f2da4ee5c2d9e5c7000b5de29d3abb72deec908db83f",
          "sha256": "899163b98e7ac2675463cd211a9cba3fc8e1d8af296dd74cc2258992bc79122d",
          "sha1": "da7af14245ed3f5a6e7a5e6ad0b3982d71150fb6",
          "md5": "cf38908ebd82a0f5cf3c931f9cf9bca6"
        }
      ]
    }
  ]
}
