{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-test",
    "version": "5.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "62bllhdns5az3hsr52svr7rfgq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xpp3",
              "module": "xpp3_min"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.3.jar",
          "url": "spring-test-5.3.3.jar",
          "size": 763132,
          "sha512": "86d647539e6876e7710dcc7d7df7a132a2c2918cba78e90dd71d8ff78d34123dcccc15e3eaaac22c03df6ef6c6e9849b6bcee74bd50c74388b62809096875a45",
          "sha256": "2348fa318b1bcdddde71e22591b2590fd2632bdaa6dd61b36363be3bd7cf525c",
          "sha1": "13f4fe0f60e2211c49c589a7e5605af580d66e63",
          "md5": "0c066e07de4c73009b0558720bcfa1f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "xpp3",
              "module": "xpp3_min"
            },
            {
              "group": "xmlpull",
              "module": "xmlpull"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-test-5.3.3.jar",
          "url": "spring-test-5.3.3.jar",
          "size": 763132,
          "sha512": "86d647539e6876e7710dcc7d7df7a132a2c2918cba78e90dd71d8ff78d34123dcccc15e3eaaac22c03df6ef6c6e9849b6bcee74bd50c74388b62809096875a45",
          "sha256": "2348fa318b1bcdddde71e22591b2590fd2632bdaa6dd61b36363be3bd7cf525c",
          "sha1": "13f4fe0f60e2211c49c589a7e5605af580d66e63",
          "md5": "0c066e07de4c73009b0558720bcfa1f9"
        }
      ]
    }
  ]
}
