{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xiu4wbhcdnfo3k3sp26u3m4ssa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.4.2.jar",
          "url": "spring-boot-starter-tomcat-2.4.2.jar",
          "size": 4796,
          "sha512": "63549ddf3d8abe215311ad29db9481513a036506c6a9901c08add1ab2ddc387012ec6dab1a69782afc8c0da35289101574d65708b12a84c75f3c117691e1c1ef",
          "sha256": "e4096b80601a26bb2dfac21422658d603995a9d8625628c6a1f8ec1b60233b28",
          "sha1": "4a43bd6c0d41cf42cea7b84ffc9d1e6e0bd2f7b0",
          "md5": "2cdd9c997a110f3fd0902febb4363be9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.glassfish",
          "module": "jakarta.el",
          "version": {
            "requires": "3.0.3"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.41"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.4.2.jar",
          "url": "spring-boot-starter-tomcat-2.4.2.jar",
          "size": 4796,
          "sha512": "63549ddf3d8abe215311ad29db9481513a036506c6a9901c08add1ab2ddc387012ec6dab1a69782afc8c0da35289101574d65708b12a84c75f3c117691e1c1ef",
          "sha256": "e4096b80601a26bb2dfac21422658d603995a9d8625628c6a1f8ec1b60233b28",
          "sha1": "4a43bd6c0d41cf42cea7b84ffc9d1e6e0bd2f7b0",
          "md5": "2cdd9c997a110f3fd0902febb4363be9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.4.2-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.4.2-javadoc.jar",
          "size": 4744,
          "sha512": "f2ed48acbd780f9167f6a6f9f974319ecf040f61aaa8443187873133857d4db8ad5828b4ace93604da0c6ff29fa6d3401e78f8fd091f3410e6d2801d092001c3",
          "sha256": "98f7cfb35d36f109c7614b1f337d5d7a93f4e3b03ce8931c42288f83b02e6f6f",
          "sha1": "8701c73f69e36390cca9871f6f7c84671a695d3b",
          "md5": "d5f385a57bd31bd945915a115fd432d3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.4.2-sources.jar",
          "url": "spring-boot-starter-tomcat-2.4.2-sources.jar",
          "size": 4743,
          "sha512": "99c152d2170bfd6324b6a7dba641ce1a8de9389ee9348d7e4b51e44b8ef7f7517a245bae7add44498e33794662bde462fbd8238c6f3d5461235fbb3a86d78b35",
          "sha256": "b17536fe1712532e46fea429ef388cbed1e62cd7f7228e37b19dc97fc4c1f8dd",
          "sha1": "feefb2c6143cab7a4734a9e64f61c0ae3c6c13bf",
          "md5": "8c5a5851d5463345301b8078a1ddcbff"
        }
      ]
    }
  ]
}
