{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "5.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "62bllhdns5az3hsr52svr7rfgq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-5.3.3.jar",
          "url": "spring-webmvc-5.3.3.jar",
          "size": 996262,
          "sha512": "a12bca5398867aa79fa6225f8f03f2c058a67333184d2082310f946bf91172aea8f10ebdca43cc0becb9326f406a01753f99cc7265881be67bebb23243e44a3a",
          "sha256": "fcd8d74bb1edc8d7c6c9291fa6008a5810b4ecfe4f4f0e2b9d886428b4a29966",
          "sha1": "a88088cbd798d681d1e219e56896eaa067c925e1",
          "md5": "e72852e831a39dd4185a2e17459a2214"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "5.3.3"
          },
          "excludes": [
            {
              "group": "xml-apis",
              "module": "xml-apis"
            },
            {
              "group": "org.apache.taglibs",
              "module": "taglibs-standard-spec"
            },
            {
              "group": "net.java.dev.msv",
              "module": "xsdlib"
            },
            {
              "group": "xpp3",
              "module": "xpp3"
            },
            {
              "group": "dom4j",
              "module": "dom4j"
            },
            {
              "group": "relaxngDatatype",
              "module": "relaxngDatatype"
            },
            {
              "group": "pull-parser",
              "module": "pull-parser"
            },
            {
              "group": "org.hamcrest",
              "module": "hamcrest-core"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-5.3.3.jar",
          "url": "spring-webmvc-5.3.3.jar",
          "size": 996262,
          "sha512": "a12bca5398867aa79fa6225f8f03f2c058a67333184d2082310f946bf91172aea8f10ebdca43cc0becb9326f406a01753f99cc7265881be67bebb23243e44a3a",
          "sha256": "fcd8d74bb1edc8d7c6c9291fa6008a5810b4ecfe4f4f0e2b9d886428b4a29966",
          "sha1": "a88088cbd798d681d1e219e56896eaa067c925e1",
          "md5": "e72852e831a39dd4185a2e17459a2214"
        }
      ]
    }
  ]
}
