{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "2.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "xiu4wbhcdnfo3k3sp26u3m4ssa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.6.28"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.6.28"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.3"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.4.2.jar",
          "url": "spring-boot-starter-test-2.4.2.jar",
          "size": 4792,
          "sha512": "2390e09ee94d387464f6c7b42ba1b79f6190468b37ab72d10dcd33eb5cfbb4cfaafa74b8e6e711bbcb886f3d510058c7ee01c644bb2e70238591d04ed932162f",
          "sha256": "b94ba6bd19d63ec93ca65d095330d0cde6ed8d6a942a35b0fc0acd085391d933",
          "sha1": "ab95d8ade94a2c67605c64e3b3db9779a2cd6388",
          "md5": "54227fdf8c581eeef2c09b60eaf1ceab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.18.1"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "3.6.28"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "3.6.28"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.3"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.7.0"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.4.2.jar",
          "url": "spring-boot-starter-test-2.4.2.jar",
          "size": 4792,
          "sha512": "2390e09ee94d387464f6c7b42ba1b79f6190468b37ab72d10dcd33eb5cfbb4cfaafa74b8e6e711bbcb886f3d510058c7ee01c644bb2e70238591d04ed932162f",
          "sha256": "b94ba6bd19d63ec93ca65d095330d0cde6ed8d6a942a35b0fc0acd085391d933",
          "sha1": "ab95d8ade94a2c67605c64e3b3db9779a2cd6388",
          "md5": "54227fdf8c581eeef2c09b60eaf1ceab"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.4.2-javadoc.jar",
          "url": "spring-boot-starter-test-2.4.2-javadoc.jar",
          "size": 4743,
          "sha512": "66b71f52727535c6602684b2013a1c4ac07fa97ad765b74524607c7d9b928f724889f52cb55c8294a216b5a295955308eb4f27cb5b13c69bccd279f59e4aeaff",
          "sha256": "15dcfe0ec810413b92867aff95b1898655a5550f4374de55833c6f9ea9497d58",
          "sha1": "39123528b6c0b5bb0d02be04da0bd4c7ea5024ae",
          "md5": "9da92264ad80ea1523b2b34c6d94fec1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.4.2-sources.jar",
          "url": "spring-boot-starter-test-2.4.2-sources.jar",
          "size": 4741,
          "sha512": "21eff579964b518189ceed5b6e81714eb5b412bb95bd781f4a11a08cff27bc0efc48a4b1251534efb5834f413c9e81529ab4aca700cbe213d9fbcb2072ef94e7",
          "sha256": "d55a926f8076725ae285428262a4149398e273ffe869913c7b06d3dc5cef7df8",
          "sha1": "927d0d835a7da9805793f54656af542432f21e79",
          "md5": "21796cf1e2847e2a766dee7ad80b94f0"
        }
      ]
    }
  ]
}
